target("Showcase")
	set_group("Examples")
	set_kind("binary")
	add_deps("NazaraAudio", "NazaraGraphics", "NazaraChipmunkPhysics2D", "NazaraNewtonPhysics3D", "NazaraWidgets")
	add_deps("PluginAssimp", { links = {} })
	add_packages("entt")
	add_files("main.cpp")
